name: prgda
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - pip:
    - ipynb==0.5.1
    - numpy==1.20
    - pandas==1.3
    - xlrd>=1.0.0
    - openpyxl==3.0
    - matplotlib==3.4
    - RISE==5.7.1